language: python
python:
  - 3.6
# command to install dependencies
install:
  - pip install -r /Users/najeer/Documents/GitHub/swe1-app/ebdjango/requirements.txt
# command to run tests
script:
  - pytest


deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>="
  secret_access_key:
    secure: "Encypted <secret-access-key>="
  region: "us-east-1"
  app: "example-app-name"
  env: "example-app-environment"
  bucket_name: "the-target-S3-bucket"