language: python
python:
  - 3.7.6
# command to install dependencies
install:
  - pip install -r ./ebdjango/requirements.txt
# command to run tests
script:
  - pytest


before_script:
  - python manage.py migrate

script:
  - python manage.py
  - python -m black . --check
  - python -m flake8 --max-line-length=92
  - python -m coverage run --source='.' manage.py test

# deploy:
#   provider: elasticbeanstalk
#   access_key_id:
#     secure: "Encrypted <access-key-id>="
#   secret_access_key:
#     secure: "Encypted <secret-access-key>="
#   region: "us-east-1"
#   app: "example-app-name"
#   env: "example-app-environment"
#   bucket_name: "the-target-S3-bucket"